### ISSUE TITLE
User model : needed fields

### ISSUE THREAD

**Issue by cturbelin** [Influenzanet/user-management-service#1]
From the last meeting : what kind of information are needed in the User model ?
- "Administrative" fields like date of creation, date of validation : useful to follow user registration & attendance of the platform (and remove not validated accounts after some time)
- number of try ? (don't know if it's useful here)
- In GPDR persp : we will need to remove personal data if the user is no longer using the service (In france we do that after 18 months) and log the action (proof of data cleaning)

Maybe we should make a minimal list :)

**Comment by phev8** [comment]
@cturbelin Thank you for your input.

Usually, we write fields like "created_at", "updated_at" then, as you also wrote, time of the last login, but also time of the last token refresh, in case someone leaves it open for all the time, or the browser remembers the token. 

By number of try, you mean if someone tries to log in with the wrong password, or what exactly?

**Comment by cturbelin** [comment]
Yes, the created_at for the account is enough to have inform about the user creation, I'm wondering about the "updated_at" because it can depend on the kind of event (change of password, token, account activation : after email validation), it's probably a good idea to have several update date, not for all fields of course :) !

For the number of try yes, and it's set to zero after a success login. It can limit the risk of hack, but it needs a way to unlock the account when the user complain of it. Of course it's just not a must have !

**Comment by phev8** [comment]
I created todos items about these ideas in the project backlog.
Feel free to reopen the issue, if you think of anything else.
We can add attributes for tracking updates of different values as it will be necessary.
